name: Deploy DevQuest

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: ssh-keyscan -p 50022 -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy frontend
        run: |
          rsync -avz --no-times --no-perms --no-owner --no-group --delete \
            --exclude 'vendor/' \
            --exclude 'node_modules/' \
            ./frontend/ \
            -e "ssh -p 50022" \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_FRONTEND_PATH }}
      
      - name: Deploy API
        run: |
          rsync -avz --no-times --no-perms --no-owner --no-group --delete \
            --exclude 'vendor/' \
            --exclude 'node_modules/' \
            ./api/ \
            -e "ssh -p 50022" \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_API_PATH }}
      
      - name: Deploy CDN assets
        run: |
          rsync -avz --no-times --no-perms --no-owner --no-group --delete \
            ./assets/ \
            -e "ssh -p 50022" \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_CDN_PATH }}


      - name: Run Composer install (frontend)
        run: |
          ssh -p 50022 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_FRONTEND_PATH }}
            composer install --no-interaction --prefer-dist --optimize-autoloader
            composer dump-autoload -o
          EOF

      # - name: Run Composer install (API)
      #   run: |
      #     ssh -p 50022 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
      #       cd ${{ secrets.DEPLOY_API_PATH }}
      #       composer install --no-interaction --prefer-dist --optimize-autoloader
      #       composer dump-autoload -o
      #     EOF
