name: Deploy DevQuest

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH connection
        run: |
          mkdir -p ~/.ssh
          # Write the key exactly as in secrets
          cat > ~/.ssh/id_ed25519 <<'EOF'
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          # Fix permissions so OpenSSH accepts it
          chmod 600 ~/.ssh/id_ed25519
      
          # Debugging: confirm perms and fingerprint
          ls -l ~/.ssh/id_ed25519
          ssh-keygen -lf ~/.ssh/id_ed25519 || true
      
          # Add host key
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
      

      - name: Deploy frontend
        run: |
          rsync -avz --delete ./frontend/ \
            -e "ssh -i ~/.ssh/id_ed25519" \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_FRONTEND_PATH }}

      - name: Deploy API
        run: |
          rsync -avz --delete ./api/ \
            -e "ssh -i ~/.ssh/id_ed25519" \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_API_PATH }}

      - name: Deploy CDN assets
        run: |
          rsync -avz --delete ./assets/ \
            -e "ssh -i ~/.ssh/id_ed25519" \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_CDN_PATH }}

      - name: Run Composer install (frontend)
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_FRONTEND_PATH }}
            composer install --no-interaction --prefer-dist --optimize-autoloader
            composer dump-autoload -o
          EOF

      - name: Run Composer install (API)
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_API_PATH }}
            composer install --no-interaction --prefer-dist --optimize-autoloader
            composer dump-autoload -o
          EOF

      - name: Fix ownership and permissions
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            sudo chown -R www-data:www-data ${{ secrets.DEPLOY_FRONTEND_PATH }}
            sudo chown -R www-data:www-data ${{ secrets.DEPLOY_API_PATH }}
            sudo chown -R www-data:www-data ${{ secrets.DEPLOY_CDN_PATH }}
          EOF

      # - name: Run database migrations (future)
      #   run: |
      #     ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
      #       cd ${{ secrets.DEPLOY_API_PATH }}
      #       php artisan migrate --force   # or doctrine:migrations:migrate
      #     EOF
